// config.example.js
// ─────────────────────────────────────────────────────────
// This file IS committed to the repo — it contains no real
// secrets. Copy it to config.js, fill in your values, and
// make sure config.js is in .gitignore.
//
// In production, config.js is auto-generated by the
// GitHub Actions deploy workflow using repository secrets.
// ─────────────────────────────────────────────────────────

window.__NX_CONFIG__ = {
  apiKey:            "REPLACE_WITH_YOUR_FIREBASE_API_KEY",
  authDomain:        "REPLACE_WITH_YOUR_AUTH_DOMAIN",
  projectId:         "REPLACE_WITH_YOUR_PROJECT_ID",
  messagingSenderId: "REPLACE_WITH_YOUR_MESSAGING_SENDER_ID",
  appId:             "REPLACE_WITH_YOUR_APP_ID"
};
